### PR TITLE
Workaround for windows on file rename for expand_libecc.py

### PR DESCRIPTION
**Pull request by Arwalk**
As the documentation for `os.rename` ( https://docs.python.org/3/library/os.html#os.rename ) says, "On Windows, if dst exists a FileExistsError is always raised."
Renaming the "curves_list.h.tmp" to "curves_list.h" on the fly fails on windows.

This modification allows the script to work properly on windows.

tested on windows 10 with python 3.9.0 and on linux (WSL) with python 3.8.2

### CODE REVIEW

**Comment by Arwalk** [comment]
Hmm, not sure why something failed on the CI! I don't think a few lines on expand_libecc.py would break everything. Probably another issue.

**Comment by rb-anssi** [comment]
Hi @Arwalk,

Thanks for your interest in libecc and for the pull request: I will review it asap!
This PR did not break the CI indeed, since CI scripts do not make use of the `expand_libecc.py` script for now (they only cross-build the library with various options). Sometimes Travis can show some unstable results on long jobs ... Let me check this.

Regards,

**Review by rb-anssi — COMMENTED** [review]
Hi @Arwalk,

Thanks for spotting this behavior on Windows! Sorry to be picky, but:
1) Can you please check the indentation of your patch, this does not seem to be compatible with the original code (on purpose?)
2) Instead of using `os.remove`, could you use the abstract function `remove_file` defined in the script?

Thanks in advance!
Regards,

**Comment by Arwalk** [comment]
Hello!

>Can you please check the indentation of your patch, this does not seem to be compatible with the original code (on purpose?)

This was indeed on purpose. os.rename is not an atomic operation on windows (which is the problem in the first place), so i preferred to ensure the file handle opened in the block created line 1288 was released before doing the workaround. I have not tested if it would work without this.

>Instead of using os.remove, could you use the abstract function remove_file defined in the script?

Done. I have no excuse, it's the line just under my modifications.

**Comment by rb-anssi** [comment]
Hi @Arwalk,

Thanks for the updated PR and for the details! (understood and agreed for the non-atomic aspect of `os.rename` on Windows).
PR merged, and CI is up and running again for this PR.

Regards,

**Pull request merged**
